packages:
  - "apps/*"
  - "packages/*"
  - "examples/**/*"
  - "services/*"
  # all internal packages except `packages/internal/_template`
  - "!packages/internal/_template"
  - "packages/internal/**"
