import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@mvdlei/ui";

import "@mvdlei/ui/styles/globals.css";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-screen w-screen relative")}>
        {children}
      </body>
    </html>
  );
}
