import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@mvdlei/ui/styles/globals.css";

import { Button } from "@mvdlei/ui/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Button />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
