name: Main (apps) Go
on:
  push:
    branches:
      - main
    paths:
      - "apps/go/**"
      - ".github/workflows/main_push_go_apps.yaml"

concurrency: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    working-directory: ./apps/go

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.21.x]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      # install
      - run: go mod download
        name: Install dependencies

      - name: Build
        # Build the main.go file in the apps/go directory
        run: go build -o main .
        env:
          CI: true
